[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "echo Starting police search app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/should_search/"
healthcheckTimeout = 300
