[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "echo building!"

[deploy]
startCommand = "echo starting!"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/"
healthcheckTimeout = 300
